infect_dashboard:
    pattern: /
    defaults: { _controller: InfectBackendBundle:Default:index }

infect_login:
    pattern:    /login
    defaults:   { _controller: InfectBackendBundle:Security:login }

infect_login_check:
    pattern:    /login/check

# Bacteria
infect_bacteria_add:
    pattern: /bacteria/add/{edit}/{id}
    defaults: { _controller: InfectBackendBundle:Bacteria:addEdit, edit: '', id: '' }

                