resistance:
    pattern:  /
    defaults: { _controller: "InfectBackendBundle:Resistance:index" }

resistance_show:
    pattern:  /{id_bacteria}.bacteria/{id_compound}.compound/show
    defaults: { _controller: "InfectBackendBundle:Resistance:show" }

resistance_new:
    pattern:  /new
    defaults: { _controller: "InfectBackendBundle:Resistance:new" }

resistance_create:
    pattern:  /create
    defaults: { _controller: "InfectBackendBundle:Resistance:create" }
    requirements: { _method: post }

resistance_edit:
    pattern:  /{id_bacteria}.bacteria/{id_compound}.compound/edit
    defaults: { _controller: "InfectBackendBundle:Resistance:edit" }

resistance_update:
    pattern:  /{id_bacteria}.bacteria/{id_compound}.compound/update
    defaults: { _controller: "InfectBackendBundle:Resistance:update" }
    requirements: { _method: post|put }

resistance_delete:
    pattern:  /{id_bacteria}.bacteria/{id_compound}.compound/delete
    defaults: { _controller: "InfectBackendBundle:Resistance:delete" }
    requirements: { _method: post|delete }
